create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null default '',
  auth text not null default '',
  user_name text null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_name_idx
  on public.push_subscriptions (user_name);

create index if not exists push_subscriptions_enabled_idx
  on public.push_subscriptions (enabled);

alter table public.push_subscriptions enable row level security;

create table if not exists public.team_messages (
  id bigint generated by default as identity primary key,
  user_name text null,
  message text not null,
  created_at timestamptz not null default now()
);

create index if not exists team_messages_created_at_idx
  on public.team_messages (created_at desc);

alter table public.team_messages enable row level security;

drop policy if exists "team_messages_select_public" on public.team_messages;
create policy "team_messages_select_public"
on public.team_messages
for select
to anon, authenticated
using (true);

drop policy if exists "team_messages_insert_public" on public.team_messages;
create policy "team_messages_insert_public"
on public.team_messages
for insert
to anon, authenticated
with check (true);
