create table if not exists public.picklist_allocation_audit (
  id bigint generated by default as identity primary key,
  picklist_item_id bigint not null,
  picklist_id text null,
  wo_number text null,
  customer_name text null,
  item_label text null,
  previous_allocated boolean not null default false,
  new_allocated boolean not null default false,
  user_name text not null,
  claimed_role text null,
  reason text null,
  note text null,
  changed_at timestamptz not null default now()
);

create index if not exists picklist_allocation_audit_item_idx
  on public.picklist_allocation_audit (picklist_item_id, changed_at desc);

create index if not exists picklist_allocation_audit_wo_idx
  on public.picklist_allocation_audit (wo_number, changed_at desc);

create index if not exists picklist_allocation_audit_user_idx
  on public.picklist_allocation_audit (user_name, changed_at desc);

alter table public.picklist_allocation_audit enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'picklist_allocation_audit'
      and policyname = 'picklist_allocation_audit_select'
  ) then
    create policy "picklist_allocation_audit_select"
      on public.picklist_allocation_audit
      for select
      to anon, authenticated
      using (true);
  end if;
end $$;
